...@theme

grid-columns: 2
grid-gap: 56

pc: パソコン {
  class: boundary
  grid-rows: 4
  grid-gap: 0
  user: 利用者・入出力 { class: identity }
  app: アプリケーション { class: app }
  os: OS { class: os }
  hardware: ハードウェア { class: hardware }
}

server: サーバー {
  class: boundary
  grid-rows: 4
  grid-gap: 0
  user: ネットワーク上の利用者 { class: identity }
  app: サーバーアプリケーション { class: app }
  os: OS { class: os }
  hardware: ハードウェア { class: hardware }
}
