...@theme

grid-rows: 2
grid-gap: 0

ubuntu: Ubuntuディストリビューション {
  class: boundary
  grid-rows: 4
  grid-gap: 0
  apps: アプリケーション・サービス { class: app }
  management: systemd・APT・設定 { class: identity }
  userspace: ライブラリ・コマンド・シェル { class: app }
  kernel: Linuxカーネル { class: os }
}

host: ハードウェアまたは仮想マシン { class: hardware }
