...@theme

direction: right

input: 標準入力 stdin {
  class: boundary
  keyboard: キーボード { class: identity }
  input_file: 入力ファイル { class: neutral }
}

process1: コマンドのプロセス { class: os }

output: 出力先 {
  class: boundary
  stdout: 標準出力 stdout { class: app }
  stderr: 標準エラー出力 stderr { class: warning }
  file: ファイルへ保存 { class: neutral }
}

process2: 次のコマンド { class: os }

input.keyboard -> process1
input.input_file -> process1: "<"
process1 -> output.stdout
process1 -> output.stderr
process1 -> output.file: ">"
process1 -> process2: "|"
