...@theme

direction: right

student_pc: 学生PC {
  class: boundary
  grid-rows: 3
  host: ホスト名 { class: neutral }
  user: ローカルユーザー { class: identity }
  files: ローカルファイル { class: app }
}

cloudshell: CloudShell {
  class: boundary
  grid-rows: 3
  host: ホスト名 { class: neutral }
  user: CloudShellのユーザー { class: identity }
  files: ホームディレクトリ { class: app }
}

ubuntu: Ubuntuサーバー {
  class: boundary
  grid-rows: 3
  host: ホスト名 { class: neutral }
  user: ssm-user { class: identity }
  files: サーバー上のファイル { class: app }
}

student_pc -> cloudshell: ブラウザ
cloudshell -> ubuntu: SSH
