...@theme

grid-columns: 2
grid-gap: 56

before: setgidなし {
  class: boundary
  grid-rows: 3
  dir: 共有ディレクトリ\n所有グループ ops { class: os }
  user: jduwriter\nプライマリグループ jduwriter { class: identity }
  file: 新規ファイル\nグループ jduwriter { class: warning }
}

after: setgidあり {
  class: boundary
  grid-rows: 3
  dir: 共有ディレクトリ\n所有グループ ops\nsetgid = 2 { class: os }
  user: jduwriter\nプライマリグループ jduwriter { class: identity }
  file: 新規ファイル\nグループ ops { class: app }
}
