...@theme

grid-columns: 2
grid-gap: 28

package: パッケージ { class: neutral }
program: プログラム\nディスク上の実行ファイル { class: hardware }
process: プロセス\n実行中のプログラム { class: app }
service: サービス\n継続して提供する機能 { class: os }
systemd: systemd\n起動・停止・監視 { class: identity }

package -> program
program -> process
systemd -> process
process -> service
