...@theme

grid-rows: 2
grid-gap: 30

update_flow: 一覧を更新する処理 {
  class: boundary
  grid-columns: 3
  metadata: リポジトリのパッケージ情報 { class: neutral }
  update: apt update { class: key }
  index: ローカルのパッケージ一覧 { class: os }
  metadata -> update
  update -> index
}

install_flow: パッケージを導入する処理 {
  class: boundary
  grid-columns: 3
  package: リポジトリのパッケージ本体 { class: hardware }
  install: apt install { class: key }
  installed: インストール済みプログラム { class: app }
  package -> install
  install -> installed
}

update_flow.index -> install_flow.install: {
  style.stroke-dash: 4
}
