#!/usr/bin/env python3
import signal
import sys
import time

running = True


def stop(_signum, _frame):
    global running
    running = False


signal.signal(signal.SIGTERM, stop)
token = sys.argv[1] if len(sys.argv) == 2 else "missing-token"
while running:
    time.sleep(1)
print(f"worker stopped: {token}", flush=True)
